# Generated by Django 3.0.4 on 2020-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalikes', '0017_auto_20200524_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
