# Generated by Django 3.0.4 on 2020-05-30 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instalikes', '0018_auto_20200525_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentsby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=1000)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalikes.post')),
            ],
        ),
    ]
