# Generated by Django 3.0.7 on 2020-07-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalikes', '0019_commentsby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
