# Generated by Django 3.0.7 on 2020-07-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalikes', '0023_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
